apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  namespace: pwn
spec:
  replicas: 3
  selector:
    matchLabels:
      role: hello
  template:
    metadata:
      labels:
        role: hello
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.41-alpine
        ports:
        - containerPort: 8080