apiVersion: batch/v1
kind: Job
metadata:
  name: sequential-countdown
spec:
  completions: 5
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: sequential-countdown
        image: ubuntu
        command:
        - "bin/bash"
        - "-c"
        - "for i in {0..15} ; do echo $i ; sleep 1; done"
      restartPolicy: Never