apiVersion: v1
kind: Namespace
metadata:
  name: cal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chk1
  namespace: cal
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.12-alpine
        env:
        - name: VARIABLE_NAME
          value: "VARIABLE_VALUE"
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 80
  revisionHistoryLimit: 50