apiVersion: v1
kind: Namespace
metadata:
  name: zz8
--- 
apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: zz8
spec:
  containers:
  - name: httpd
    image: httpd:2.4.39-alpine
    env:
    - name: NAME01
      value: "VALUE01"
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8081