apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: development
spec:
  containers:
  - name: nginx
    image: nginx:1.16.1-alpine
    env:
    - name: SECRET_TKN
      valueFrom:
        secretKeyRef:
          name: xh8jqk7z
          key: tkn
    ports:
    - containerPort: 80