pipeline {
   agent any

   stages {
      stage('Cleaning up') {
         steps {
             bat 'kubectl delete statefulset mysql'
             bat 'kubectl get pods -l app=mysql'
             bat 'kubectl delete configmap,service,pvc -l app=mysql'
         }
      }
      stage('Creating Up') {
         steps {
            bat 'kubectl create -f mysql-configmap.yaml'
            bat 'kubectl create -f mysql-services.yaml'
            bat 'kubectl create -f mysql-storageclass.yaml'
            bat 'kubectl create -f mysql-statefulset.yaml'

            bat 'kubectl describe pv'
            bat 'kubectl describe pvc'

            bat 'kubectl get pods -l app=mysql --watch'
            bat 'kubectl get storageclass'
            bat 'kubectl get statefulset'
         }
      }
   }
}
