apiVersion: v1
kind: Pod
metadata:
creationTimestamp: null
labels:
run: pod
name: pod
namespace: development
spec:
schedulerName: kube-scheduler-amazing
containers:
  - image: nginx:1.16.1-alpine
    name: pod
    resources: {}
    dnsPolicy: ClusterFirst
    restartPolicy: Always
    status: {}