apiVersion: v1
kind: Pod
metadata:
creationTimestamp: null
labels:
run: pod2
name: pod2
spec:
containers:
  - image: nginx:1.16.1-alpine
    name: pod2
    resources: {}
    dnsPolicy: ClusterFirst
    restartPolicy: Always
    status: {}